# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-07 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childrenrecipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='tag',
            new_name='tags',
        ),
        migrations.AddField(
            model_name='recipe',
            name='collect_quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='pageviews',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='time_weight',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
