# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-16 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childrenrecipe', '0002_auto_20161107_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('exihibitpic', models.ImageField(upload_to='exhibited_picture/%Y/%m/%d')),
                ('headline', models.CharField(max_length=100)),
                ('subhead', models.CharField(max_length=100)),
                ('pagetype', models.CharField(max_length=40)),
                ('reference_id', models.IntegerField()),
                ('show', models.IntegerField()),
                ('pubdate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DetailsListMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LargeViewsMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('guide_language', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=100)),
                ('exihibitpic', models.ImageField(upload_to='exhibited_picture/%Y/%m/%d')),
                ('url', models.URLField()),
                ('seq', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='procedure',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='create_time',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='largeviewsmode',
            name='recipes',
            field=models.ManyToManyField(to='childrenrecipe.Recipe'),
        ),
        migrations.AddField(
            model_name='detailslistmode',
            name='webpages',
            field=models.ManyToManyField(to='childrenrecipe.WebPage'),
        ),
    ]
