# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-19 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('childrenrecipe', '0002_auto_20161107_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('exihibitpic', models.ImageField(upload_to='exhibited_picture/%Y/%m/%d')),
                ('headline', models.CharField(max_length=100)),
                ('subhead', models.CharField(max_length=100)),
                ('pagetype', models.IntegerField()),
                ('reference_id', models.IntegerField()),
                ('seq', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DetailsListMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DetailsListModeWebPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField()),
                ('detailslistmode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='childrenrecipe.DetailsListMode')),
            ],
        ),
        migrations.CreateModel(
            name='LargeViewsMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('guide_language', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='LargeViewsModeRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField()),
                ('largeviewsmode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='childrenrecipe.LargeViewsMode')),
            ],
        ),
        migrations.CreateModel(
            name='WebPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=100)),
                ('exihibitpic', models.ImageField(upload_to='exhibited_picture/%Y/%m/%d')),
                ('url', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='procedure',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='create_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='recommend',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='largeviewsmoderecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='childrenrecipe.Recipe'),
        ),
        migrations.AddField(
            model_name='largeviewsmode',
            name='recipes',
            field=models.ManyToManyField(through='childrenrecipe.LargeViewsModeRecipe', to='childrenrecipe.Recipe'),
        ),
        migrations.AddField(
            model_name='detailslistmodewebpage',
            name='webpage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='childrenrecipe.WebPage'),
        ),
        migrations.AddField(
            model_name='detailslistmode',
            name='webpages',
            field=models.ManyToManyField(through='childrenrecipe.DetailsListModeWebPage', to='childrenrecipe.WebPage'),
        ),
    ]
