# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-15 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childrenrecipe', '0002_auto_20161107_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekRecommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('guide_language', models.TextField()),
                ('pubdate', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='procedure',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='create_time',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='weekrecommend',
            name='recipes',
            field=models.ManyToManyField(to='childrenrecipe.Recipe'),
        ),
    ]
