# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-03 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childrenrecipe', '0002_auto_20161103_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='collection',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='pageviews',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
