# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-04 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('childrenrecipe', '0003_auto_20161103_1918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='collection',
            new_name='collect_quantity',
        ),
    ]
