# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-15 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childrenrecipe', '0003_auto_20161115_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodKnowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=100)),
                ('exihibitpic', models.ImageField(upload_to='exhibited_picture/%Y/%m/%d')),
            ],
        ),
    ]
