# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-15 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childrenrecipe', '0004_foodknowledge'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodknowledge',
            name='headline',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodknowledge',
            name='subhead',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodknowledge',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weekrecommend',
            name='exihibitpic',
            field=models.ImageField(default=1, upload_to='exhibited_picture/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weekrecommend',
            name='subtitle',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weekrecommend',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weekrecommend',
            name='guide_language',
            field=models.TextField(blank=True),
        ),
    ]
