# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-16 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childrenrecipe', '0004_auto_20161116_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='show',
            new_name='seq',
        ),
        migrations.AlterField(
            model_name='card',
            name='reference_id',
            field=models.IntegerField(),
        ),
    ]
