# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-16 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childrenrecipe', '0005_auto_20161116_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='pagetype',
            field=models.IntegerField(),
        ),
    ]
