# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-17 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childrenrecipe', '0006_auto_20161116_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailslistmode',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='largeviewsmode',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
