# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-17 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childrenrecipe', '0007_auto_20161117_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='detailslistmode',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='largeviewsmode',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='recommend',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
