# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-17 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childrenrecipe', '0008_auto_20161117_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='seq',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
